#!/usr/bin/env node
// tools/update-dict.mjs — daily dictionary updater for han-tu-app
//
// The data flows through three files:
//   data/ds_cac_chu.txt   you edit this (the new characters)
//   data/dictionary.json  source of truth: { "字": { "hv": "...", "nghia": "..." } }
//   js/dictionary-data.js the ONLY dictionary the browser loads (window.HAN_VIET_DICT)
//
// This script keeps them in sync in one command:
//   1. Read ds_cac_chu.txt, extract unique CJK characters (same regex as the app).
//   2. Find characters that have no entry in dictionary.json yet.
//   3. Prompt you for the Hán Việt reading + nghĩa of each new character.
//   4. Write dictionary.json  — always valid JSON (JSON.stringify can't emit a trailing comma).
//   5. Regenerate js/dictionary-data.js from dictionary.json.
//   6. Bump the ?v= cache-buster on the <script> tag in index.html so browsers refetch.
//
// Usage:
//   node tools/update-dict.mjs           interactive — prompt for each new character
//   node tools/update-dict.mjs --regen   no prompts — just rebuild the .js + bump cache
//                                         (also use this after hand-editing dictionary.json)
//
// Path overrides (for testing): HANTU_LIST, HANTU_JSON, HANTU_JS, HANTU_HTML

import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const LIST = process.env.HANTU_LIST || path.join(ROOT, 'data', 'ds_cac_chu.txt');
const JSON_PATH = process.env.HANTU_JSON || path.join(ROOT, 'data', 'dictionary.json');
const JS_PATH = process.env.HANTU_JS || path.join(ROOT, 'js', 'dictionary-data.js');
const HTML_PATH = process.env.HANTU_HTML || path.join(ROOT, 'index.html');

const CJK = /[㐀-鿿]/g; // CJK Ext-A + main block — identical to the app's char filter
const EOL = '\r\n';             // repo files are CRLF; keep diffs minimal on Windows

const read = (p) => fs.readFileSync(p, 'utf8');
const write = (p, s) => fs.writeFileSync(p, s);
const regenOnly = process.argv.includes('--regen');

// --- 1. load the character list (unique, in first-appearance order) ---
const listChars = [];
{
  const seen = new Set();
  for (const c of read(LIST).match(CJK) || []) {
    if (!seen.has(c)) { seen.add(c); listChars.push(c); }
  }
}

// --- 2. load dictionary + find characters with no entry yet ---
const dict = JSON.parse(read(JSON_PATH));
const newChars = listChars.filter(c => !Object.prototype.hasOwnProperty.call(dict, c));

// --- 3. prompt for the new characters ---
async function promptForNew() {
  const rl = readline.createInterface({ input: process.stdin });
  const lines = rl[Symbol.asyncIterator]();
  // Print a prompt, then read one line. Returns null at EOF (Ctrl-D / closed pipe).
  const askLine = async (q) => {
    process.stdout.write(q);
    const { value, done } = await lines.next();
    return done ? null : value.trim();
  };
  const askRequired = async (q) => {
    let v = '';
    while (!v) {
      const line = await askLine(q);
      if (line === null) { rl.close(); throw new Error('Input ended before all characters were entered — nothing was written.'); }
      v = line;
    }
    return v;
  };
  console.log(`\n${newChars.length} new character(s) in ${path.basename(LIST)}: ${newChars.join(' ')}\n`);
  for (const c of newChars) {
    const hv = await askRequired(`${c}  hán việt : `);
    const nghia = await askRequired(`${c}  nghĩa    : `);
    dict[c] = { hv, nghia }; // appended in list order; JSON.stringify preserves insertion order
  }
  rl.close();
}

// --- 4/5/6. writers ---
function writeJson(obj) {
  write(JSON_PATH, JSON.stringify(obj, null, 2).replace(/\n/g, EOL) + EOL);
}

function writeJs(obj) {
  const header =
    '// Auto-generated Hán-Việt dictionary' + EOL +
    '// Format: char -> { hv: "Han-Viet reading", nghia: "Vietnamese meaning" }' + EOL +
    '// Generated by tools/update-dict.mjs — do not hand-edit; edit data/dictionary.json instead' + EOL;
  write(JS_PATH, header + 'window.HAN_VIET_DICT = ' + JSON.stringify(obj, null, 2).replace(/\n/g, EOL) + ';' + EOL);
}

function bumpCacheBuster() {
  const hash = crypto.createHash('sha256').update(read(JS_PATH)).digest('hex').slice(0, 8);
  const re = /(src=")(js\/dictionary-data\.js)(\?v=[a-f0-9]+)?(")/;
  let html = read(HTML_PATH);
  if (!re.test(html)) {
    console.warn('⚠ could not find the dictionary-data.js <script> tag in index.html — skipping cache-bust');
    return null;
  }
  write(HTML_PATH, html.replace(re, `$1$2?v=${hash}$4`));
  return hash;
}

// --- run ---
(async () => {
  if (regenOnly) {
    if (newChars.length) {
      console.log(`(--regen) ${newChars.length} character(s) have no entry and are left as-is: ${newChars.join(' ')}`);
    }
  } else if (newChars.length === 0) {
    console.log(`No new characters — dictionary.json already covers ${path.basename(LIST)}. Rebuilding outputs…`);
  } else {
    await promptForNew();
  }

  writeJson(dict);
  writeJs(dict);
  const hash = bumpCacheBuster();

  JSON.parse(read(JSON_PATH)); // sanity: re-parse what we just wrote

  const total = Object.keys(dict).length;
  console.log(`\n✓ ${path.relative(ROOT, JSON_PATH)}   valid (${total} entries)`);
  console.log(`✓ ${path.relative(ROOT, JS_PATH)}  regenerated (${total} entries)`);
  if (hash) console.log(`✓ ${path.relative(ROOT, HTML_PATH)}             cache version → ?v=${hash}`);
  console.log('\nNext:  git add -A && git commit -m "Add new characters" && git push');
})().catch((err) => {
  console.error('\n✗ ' + err.message);
  process.exit(1);
});
